#!/usr/bin/env python3
"""Thin CLI around issue_live_pilot_authorization.

This exists so the Windows and POSIX operational wrappers can issue a
fresh, nonce-bound authorization and immediately consume it in the same
invocation, without the operator ever seeing or transcribing the nonce
(it is internally generated by issue_live_pilot_authorization itself).

On success, prints exactly the nonce to stdout (nothing else) so a
calling shell can capture it directly. On any failure, prints a message
to stderr and exits non-zero; nothing is printed to stdout in that case.

This script does not connect to a broker and cannot place, cancel,
modify, retry, flatten, or close an order -- see
live_pilot_one_shot_authorization.py's own module docstring.
"""
from __future__ import annotations

import argparse
from pathlib import Path
import sys

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "src"))

from ai_asset_platform.execution.live_pilot_one_shot_authorization import (
    issue_live_pilot_authorization,
)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--confirmation", required=True)
    parser.add_argument("--intent-id", required=True)
    parser.add_argument("--ticker", required=True)
    parser.add_argument("--side", required=True)
    parser.add_argument("--quantity", required=True, type=int)
    parser.add_argument("--limit-price", required=True, type=float)
    parser.add_argument("--estimated-notional-jpy", required=True, type=float)
    parser.add_argument("--account-fingerprint", required=True)
    parser.add_argument("--endpoint-port", required=True, type=int)
    parser.add_argument("--authorization-dir", type=Path)
    args = parser.parse_args(argv)

    kwargs = dict(
        confirmation=args.confirmation,
        intent_id=args.intent_id,
        ticker=args.ticker,
        side=args.side,
        quantity=args.quantity,
        limit_price=args.limit_price,
        estimated_notional_jpy=args.estimated_notional_jpy,
        account_fingerprint=args.account_fingerprint,
        endpoint_port=args.endpoint_port,
    )
    if args.authorization_dir is not None:
        kwargs["authorization_dir"] = args.authorization_dir

    try:
        authorization = issue_live_pilot_authorization(**kwargs)
    except (PermissionError, ValueError) as exc:
        print(f"BLOCKED: {exc}", file=sys.stderr)
        return 2

    sys.stdout.write(authorization.nonce)
    return 0


if __name__ == "__main__":
    sys.exit(main())
